DROP TABLE IF EXISTS movie CASCADE;
CREATE TABLE movie
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    legacy_id      INTEGER,
    public_id      UUID,
    movie_name     VARCHAR(255),
    movie_synopsis TEXT,
    movie_category VARCHAR(255),
    movie_year     INTEGER,
    movie_director VARCHAR(255),
    PRIMARY KEY (id)
);
