CREATE TABLE movie
(
    id_movie   NUMBER(24,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 0 NOMAXVALUE NOT NULL,
    id_legacy  NUMBER(24,0) NOT NULL,
    id_public  STRING AS UUID GENERATED BY DEFAULT,
    movie_name VARCHAR(100),
    CONSTRAINT movie_pk PRIMARY KEY (id_movie) USING INDEX TABLESPACE TSI(MOVIE_API) 01
);

COMMENT
ON TABLE movie IS '[NOT_SECURITY_APPLY] Table to store information about movies from the API';
COMMENT
ON COLUMN movie.id_movie IS '[NOT_SECURITY_APPLY] Primary key identifier for internal database queries';
COMMENT
ON COLUMN movie.id_legacy IS '[NOT_SECURITY_APPLY] Identifier used for API backward compatibility in V1';
COMMENT
ON COLUMN movie.id_public IS '[NOT_SECURITY_APPLY] More secure identifier for API user queries';
COMMENT
ON COLUMN movie.movie_name IS '[NOT_SECURITY_APPLY] Field used to store the name of the movie.';
