CREATE TABLE MOVIE_STATISTIC
(
    PUBLIC_ID      VARCHAR2(36)  NOT NULL,
    MOVIE_NAME     VARCHAR2(100) NOT NULL,
    SEARCH_COUNTER NUMBER(10,0)  DEFAULT 0 NOT NULL,
    CONSTRAINT MOVIE_STATISTIC_PK PRIMARY KEY (PUBLIC_ID)
);

COMMENT
ON TABLE MOVIE_STATISTIC IS '[NOT_SECURITY_APPLY] Table to store statistics related to movies, such as the number of searches.';
COMMENT
ON COLUMN MOVIE_STATISTIC.PUBLIC_ID IS '[NOT_SECURITY_APPLY] Unique identifier for the movie, used as a foreign key to link with the MOVIE table.';
COMMENT
ON COLUMN MOVIE_STATISTIC.MOVIE_NAME IS '[NOT_SECURITY_APPLY] Name of the movie for reference in statistics.';
COMMENT
ON COLUMN MOVIE_STATISTIC.SEARCH_COUNTER IS '[NOT_SECURITY_APPLY] Counter to track how many times the movie has been searched for in the system.';

CREATE INDEX MOVIE_STATISTIC_IDX01 ON MOVIE_STATISTIC (MOVIE_NAME);
CREATE INDEX MOVIE_STATISTIC_IDX02 ON MOVIE_STATISTIC (SEARCH_COUNTER);
