CREATE TABLE USER_ROLES
(
    USER_ID VARCHAR2(36) NOT NULL,
    ROLE_ID NUMBER(24,0) NOT NULL,
    CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT USER_ROLES_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT USER_ROLES_FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID) ON DELETE CASCADE
);

COMMENT
ON TABLE USER_ROLES IS '[NOT_SECURITY_APPLY] Table to store the many-to-many relationship between users and roles.';
COMMENT
ON COLUMN USER_ROLES.USER_ID IS '[NOT_SECURITY_APPLY] Foreign key to the USERS table, representing the user.';
COMMENT
ON COLUMN USER_ROLES.ROLE_ID IS '[NOT_SECURITY_APPLY] Foreign key to the ROLES table, representing the role.';

CREATE INDEX USER_ROLES_IDX01 ON USER_ROLES (USER_ID);
CREATE INDEX USER_ROLES_IDX02 ON USER_ROLES (ROLE_ID);